name: first workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print this is buil job
        run: echo 'build job'
    
  test:
    runs-on: window-latest
    steps:
      - name: Print test - chrome
        run: echo 'test chrome'
      - name: Print test - edge
        run: echo 'test edge'

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print deploy
        run: echo 'deploy'
